#!/bin/bash

set -e

read -p 'Keycloak Base URL (http://localhost:8081): ' kc_base_url
read -p 'Realm: (ersd) ' realm
read -p 'Client: (ersd-app) ' client
read -p 'Test User Username: ' test_username
read -s -p $'Test User Password: \n' test_password
read -p 'ERSD Base URL (http://localhost:3333): ' ersd_base_url
read -p 'Test Email Subject: (ERSD Administrative Test) ' test_email_subject
read -p 'Test Email Body: (ERSD Administrative Test Message) ' test_email_body

kc_base_url=${kc_base_url:-'http://localhost:8081'}
ersd_base_url=${ersd_base_url:-'http://localhost:3333'}
realm=${realm:-ersd}
client=${client:-ersd-app}
test_email_subject=${test_email_subject:-'ERSD Administrative Test'}
test_email_body=${test_email_body:-'ERSD Administrative Test Message'}

res=$(curl -sS --data-urlencode 'username='$test_username --data-urlencode 'password='$test_password -d 'grant_type=password&client_id='$client -X POST $kc_base_url/auth/realms/$realm/protocol/openid-connect/token)
token=$(echo $res | jq -r '.access_token')

if [ $token == 'null' ]; then
echo 'Unable to fetch token.'
echo $res
exit 1
fi

echo 'Testing Administrative Email Blast'
curl -X POST -H 'content-type: application/json' -H 'Authorization: Bearer '$token -d '{"subject":"'$test_email_subject'","message":"'$test_email_body'"}' $ersd_base_url/api/user/email
